### ISSUE TITLE
add palindrome linked list question

### ISSUE THREAD

**Issue by Yash-Var** [Yash-Var/100_days_of_dsa#1]

**Comment by acash1809** [comment]
sir assign this issue to me

**Comment by Ujjwal-soni98** [comment]
@Yash-Var i have made a pr review it ...

**Comment by Yash-Var** [comment]
@acash1809 i am open new issue you can work on that...

**Comment by acash1809** [comment]
@Yash-Var  ok sir , assign that issue to me.
